// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uucyuqqpdfopzpnsdetx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1Y3l1cXFwZGZvcHpwbnNkZXR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1OTczNTIsImV4cCI6MjA3MjE3MzM1Mn0.4rM5a72J1NeAuWrjodMqtR6EAORY4uHD9X1h0zcp7JY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});